### ISSUE TITLE
When to open source code?

### ISSUE THREAD

**Issue by leexinhao** [Moohnai/MOFO#1]

**Comment by Moohnai** [comment]
Hi @leexinhao, the code is now available

**Comment by leexinhao** [comment]
> Hi @leexinhao, the code is now available

Thanks for your nice work! And I would like to know whether you have conducted experiments on kinetics dataset or ViT-L. From several concurrent works using motion, it seems that the results on vit-L are not good.

**Comment by Moohnai** [comment]
Thanks @leexinhao. I only tried on SSV2 and Epic-Kitchens using ViT-Base.
